### ISSUE TITLE
Milestone Backlog Summary

### ISSUE THREAD

**Issue by stuartshay** [stuartshay/AzureDevOpsKats#561]
- [ ] 1 - Lambda Task Timeout

Document/Enhance/Test Task Timeout, 

- Need Logging/Dashboard Entry, 
- Email to determine if Development ECS Task has been removed 

- [ ] 2 - Autoscale 

Add Autoscale Options 
- Prerequisites (Create Load Generator JMeter, locust.io) 
- Determine Load from Health Check Status

- [ ] 3 - Selenium Test - Git Actions

Add Docker Image Caching 

- [ ] 4 - Docker Buildx Graviton2

If possible build for Muli-Arch Docker Image for both  x64/arm64 to support Graviton2 ECS Cluster

**Bug** In Docker Bulidx Implementation AMD64/ARM64 Images can be built but will require separate workflows.

https://github.com/docker/build-push-action/blob/master/docs/advanced/multi-platform.md

![image](https://user-images.githubusercontent.com/887805/149831283-2e7ed039-12d7-47c3-9d33-9a9bfce12cfc.png)

![image](https://user-images.githubusercontent.com/887805/149831359-95d2ddda-b33a-4463-a881-610244f7727e.png)

**Comment by stuartshay** [comment]
Deployment by Branch
