### ISSUE TITLE
Milestone #5

### ISSUE THREAD

**Issue by stuartshay** [stuartshay/AzureDevOpsKats#599]
- [x] 1 - Selenium Test - Git Actions

Smoke Test/Screen Shot - Save a screen shot of the deployed ECS Container using Selenium 
Add the Saved Image to Artifacts in Github Action

Basic Example:
https://github.com/ubidots/docker-selenium-screenshot

**Issue:**
https://github.com/stuartshay/AzureDevOpsKats/issues/596

- [x] 2 - Create/implement  AWS Cost Explorer 

Create 2 Dashboards for Billing Summary for Devlop/Master listing all services 

- [x] 3 - Create EBS Shared Volume for Devlop/Master

Add Volume Mount to the the Container for saving images,  
Add a Few Samples to the Volume so connectivity can be tested 

**Mounted Folder: /images**
```
Development 
Master
```
- [x] 4 Determine Best Tool to use for Load Generation

**Comment by chiplonton** [comment]
#1, it is done
#2, I need to wait for 24h to Cost Allocation Tags activate, then we can create a report for develop and master
#3, it sone, not yet tested, please help test it
#4, please review this tool https://gettaurus.org/

**Comment by chiplonton** [comment]
fixed Cost Explorer missing ECS cost
![image](https://user-images.githubusercontent.com/95140051/150922013-4cae2c4b-c904-4437-be22-c9ad6e0c08d6.png)
