### ISSUE TITLE
Milestone #6

### ISSUE THREAD

**Issue by stuartshay** [stuartshay/AzureDevOpsKats#605]
- [x]  1 - Git Workflow Deployment

**Master  Branch**  is always pushed to Master
**Develop  Branch** is always pushed to Devlop

![image](https://user-images.githubusercontent.com/887805/150667932-e1bcf747-55a5-4853-9787-e2c98fd84e25.png)

All Other Branches can **manually** be pushed to develop using the workflow_dispatch 

![image](https://user-images.githubusercontent.com/887805/150667358-c6d7bf97-2a66-48f0-8eb8-03faff1eaa2e.png)

- [ ] 2, JS test - 

If Needed Merge JIN Branch into Master to Create JS-Test Step.

Instructions.
https://github.com/stuartshay/AzureDevOpsKats/blob/JIN/src/AzureDevOpsKats.Web/ClientApp/TestInstruction.txt

![image](https://user-images.githubusercontent.com/887805/150667662-0259d7b5-1183-449a-9720-7f65c5281d07.png)

- [x] 3, Create Jumpbox/Edge Node VM - only need 1 VM  

Basic Setup - Remote RDP,  VS Code, Docker. (More Utilities to be added Latter

- [x] 4 ECS agent calling SSM instead of application

**Comment by chiplonton** [comment]
#1, done, the code is ready on develop branch, not yet merged to master
#2, how do we set the URL to the JS test, is it possible to support from command arg or  OS ENV?

**Comment by stuartshay** [comment]
Merged Code into Master, to Test and Close Logging Issues, 

For #2 Lets go over this, I have a feeling this testing framework is not complete it may require more work before it is ready,

**Comment by chiplonton** [comment]
#3, done, please use VNC client to connect the Jumpbox node, a password will send via Skype
#4, we need to define which SSM params which ECS will get during setup container
