### ISSUE TITLE
Milestone #7

### ISSUE THREAD

**Issue by stuartshay** [stuartshay/AzureDevOpsKats#606]
- [x] 1 Setup Terraform Cloud/Github Actions 

Update Existing TF Project to Use Terraform Cloud   (Credentials Provided)
https://app.terraform.io/session

**GitHub Actions**
https://github.com/ManagedKube/kubernetes-ops 

**Reference Course**  (Good Example using EKS/Terraform Cloud)
https://app.pluralsight.com/library/courses/eks-getting-started/table-of-contents

- [ ] 2 - Diagram and Documentation

Create a Network Diagram, (Using the Standard AWS Shapes)

**Example:**
https://github.com/ManagedKube/kubernetes-ops/blob/main/docs/images/aws-kops/Topology-aws-kops.png

- [ ] 3 - Lambda Task Timeout

Document/Enhance/Test Task Timeout, 

- Need Logging/Dashboard Entry, 
- Email to determine if Development ECS Task has been removed
