### ISSUE TITLE
Milestone #7B

### ISSUE THREAD

**Issue by stuartshay** [stuartshay/AzureDevOpsKats#650]
- [x] 1 - Terraform Jumpbox 

Use workflow_dispatch to Apply/Destroy Terrafrom - Remove Master Merge

![image](https://user-images.githubusercontent.com/887805/154615507-244056fe-9a7b-4817-b679-fe592e7081bb.png)

- [x] 2 - Ansible Jumpbox playbook
https://github.com/marketplace/actions/run-ansible-playbook
https://www.ansible.com/blog/ansible-linting-with-github-actions

- [x] 3 Terraform Fix Directory Structure

Use following Model

https://github.com/aws-samples/amazon-ecs-fullstack-app-terraform/tree/main/Infrastructure
https://www.hashicorp.com/resources/a-practitioner-s-guide-to-using-hashicorp-terraform-cloud-with-github

```
-Structure
	- Modules/{ecs, jumpbox, lambda}
	- Templates
	- dev/
		+ main.tf
		...
	- prod
		+ main.tf
		...
```
- [ ] 4 - Lambda Task Timeout

Document/Enhance/Test Task Timeout, 

- Need Logging/Dashboard Entry, 
- Email to determine if Development ECS Task has been removed
